# Generated by Django 4.1.13 on 2025-04-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="updated_at",
        ),
    ]
