# Generated by Django 3.2.25 on 2025-02-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopInfinity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshop',
            name='updatd_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
