# Generated by Django 3.2.25 on 2025-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopInfinity', '0002_myshop_updatd_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshop',
            name='complete_payment',
            field=models.BooleanField(default=True),
        ),
    ]
